"""
DroidRecon - Obfuscation & Packing Detector
Author: mahmudul0x1

Detects ProGuard/R8/DexGuard obfuscation, string encryption,
and app packing/shielding — helps calibrate confidence of other findings.
"""

import os
import re
import zipfile
from pathlib import Path
from typing import Dict, List
from rich.console import Console

console = Console()

# Known packing/shielding signatures
PACKER_SIGNATURES = {
    "DexGuard":          ["com/guardsquare/dexguard", "GuardSquare", "DexGuard"],
    "Appdome":           ["com/appdome", "Appdome", "appdome"],
    "SecNeo":            ["com/secneo", "SecNeo"],
    "Bangcle":           ["com/secshell", "bangcle"],
    "Qihoo 360 (Jiagu)": ["com/qihoo/360", "jiagu", "360safe"],
    "Tencent Legu":      ["com/tencent/legu", "legu"],
    "Alibaba (walle)":   ["com/alibaba/wireless", "com/taobao/wireless"],
    "NQ Shield":         ["com/nq/android"],
    "iJiami":            ["com/ijiami"],
    "Allatori":          ["com/allatori"],
    "ProGuard":          ["proguard/", "# Generated by ProGuard"],
}

# Short class name pattern (likely obfuscated)
SHORT_CLASS_RE = re.compile(r'^[a-z]{1,3}$')
SINGLE_CHAR_RE = re.compile(r'^[a-zA-Z]$')

# String encryption indicators
STRING_ENCRYPTION_PATTERNS = [
    re.compile(r'invoke-static.*decrypt.*String', re.IGNORECASE),
    re.compile(r'invoke-static.*deobfuscate', re.IGNORECASE),
    re.compile(r'com/.*StringEncrypt', re.IGNORECASE),
    re.compile(r'invoke-static.*\[B.*Ljava/lang/String', re.IGNORECASE),  # byte[] -> String decrypt
]

# Reflection obfuscation patterns
REFLECTION_PATTERNS = [
    re.compile(r'Class\.forName\(', re.IGNORECASE),
    re.compile(r'getDeclaredMethod|getDeclaredField', re.IGNORECASE),
    re.compile(r'invoke.*reflect', re.IGNORECASE),
]


class ObfuscationDetector:
    """
    Analyzes APK for signs of code obfuscation, string encryption, and packing.
    Returns a confidence score and details.
    """

    def __init__(self, apk_path: str):
        self.apk_path = apk_path

    def analyze(self, decompiled_dir: str = None) -> Dict:
        result = {
            "obfuscation_score": 0,        # 0-100
            "obfuscation_level": "None",    # None / Low / Medium / High / Packed
            "obfuscated": False,
            "packers_detected": [],
            "indicators": [],
            "string_encryption": False,
            "reflection_heavy": False,
            "short_class_ratio": 0.0,
            "renamed_classes": 0,
            "total_classes": 0,
            "dex_count": 0,
            "multidex": False,
        }

        # DEX analysis from APK ZIP
        dex_info = self._analyze_dex_files()
        result.update(dex_info)

        # Packer detection from APK ZIP
        packer_results = self._detect_packers()
        result["packers_detected"] = packer_results

        if decompiled_dir and os.path.exists(decompiled_dir):
            source_results = self._analyze_source(decompiled_dir)
            result.update(source_results)

        # Compute score
        result["obfuscation_score"] = self._compute_score(result)
        result["obfuscation_level"] = self._score_to_level(result["obfuscation_score"])
        result["obfuscated"] = result["obfuscation_score"] >= 40

        return result

    def _analyze_dex_files(self) -> Dict:
        result = {"dex_count": 0, "multidex": False, "total_classes": 0, "renamed_classes": 0}
        try:
            with zipfile.ZipFile(self.apk_path, "r") as z:
                dex_files = [n for n in z.namelist() if re.match(r"classes\d*\.dex", n)]
                result["dex_count"] = len(dex_files)
                result["multidex"] = len(dex_files) > 1

                # Count classes from DEX (basic string scan for type descriptors)
                short_count = 0
                total_count = 0
                for dex_file in dex_files[:3]:  # Limit to first 3 DEX files
                    data = z.read(dex_file)
                    # Find class descriptors: L[package/path/ClassName];
                    classes = re.findall(rb'L([a-zA-Z0-9_$/<>;]+);', data)
                    for cls in classes:
                        try:
                            cls_str = cls.decode("utf-8", errors="ignore")
                            simple_name = cls_str.split("/")[-1].replace(";", "")
                            total_count += 1
                            if SHORT_CLASS_RE.match(simple_name) or SINGLE_CHAR_RE.match(simple_name):
                                short_count += 1
                        except Exception:
                            pass

                result["total_classes"] = total_count
                result["renamed_classes"] = short_count
                result["short_class_ratio"] = round(short_count / max(total_count, 1), 3)
        except Exception as e:
            result["dex_error"] = str(e)
        return result

    def _detect_packers(self) -> List[str]:
        detected = []
        try:
            with zipfile.ZipFile(self.apk_path, "r") as z:
                names_str = "\n".join(z.namelist()).lower()
                # Also check first 50KB of each DEX
                dex_content = b""
                for name in z.namelist():
                    if name.endswith(".dex"):
                        try:
                            dex_content += z.read(name)[:51200]
                        except Exception:
                            pass

                dex_str = dex_content.decode("utf-8", errors="ignore").lower()
                combined = names_str + "\n" + dex_str

                for packer_name, signatures in PACKER_SIGNATURES.items():
                    if any(sig.lower() in combined for sig in signatures):
                        detected.append(packer_name)
        except Exception:
            pass
        return detected

    def _analyze_source(self, decompiled_dir: str) -> Dict:
        result = {
            "string_encryption": False,
            "reflection_heavy": False,
            "indicators": [],
        }
        string_enc_hits = 0
        reflection_hits = 0
        files_checked = 0
        max_files = 500  # Limit for performance

        for root, _, files in os.walk(decompiled_dir):
            for fname in files:
                if files_checked >= max_files:
                    break
                ext = Path(fname).suffix.lower()
                if ext not in (".smali", ".java", ".kt"):
                    continue

                fpath = os.path.join(root, fname)
                try:
                    with open(fpath, "r", errors="ignore") as f:
                        content = f.read()

                    for pattern in STRING_ENCRYPTION_PATTERNS:
                        if pattern.search(content):
                            string_enc_hits += 1
                            break

                    for pattern in REFLECTION_PATTERNS:
                        if pattern.search(content):
                            reflection_hits += 1
                            break

                    files_checked += 1
                except Exception:
                    pass

        if string_enc_hits > 3:
            result["string_encryption"] = True
            result["indicators"].append(f"String encryption detected ({string_enc_hits} patterns)")

        if reflection_hits > 10:
            result["reflection_heavy"] = True
            result["indicators"].append(f"Heavy reflection usage ({reflection_hits} occurrences)")

        return result

    def _compute_score(self, result: Dict) -> int:
        score = 0

        # Short class ratio is the strongest obfuscation signal
        ratio = result.get("short_class_ratio", 0)
        if ratio > 0.5:
            score += 40
        elif ratio > 0.3:
            score += 25
        elif ratio > 0.1:
            score += 10

        # Packer detection is definitive
        if result.get("packers_detected"):
            score += 35

        # String encryption
        if result.get("string_encryption"):
            score += 15

        # Heavy reflection
        if result.get("reflection_heavy"):
            score += 10

        # MultiDEX alone isn't obfuscation but paired with other signals
        if result.get("multidex") and ratio > 0.2:
            score += 5

        return min(score, 100)

    def _score_to_level(self, score: int) -> str:
        if score == 0:
            return "None"
        elif score < 20:
            return "Low"
        elif score < 40:
            return "Medium"
        elif score < 70:
            return "High"
        else:
            return "Packed/Heavily Obfuscated"
